modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="watersource"
version="1.0.0"
displayName="Water Source"
credits="Lemon Slice Studio"
authors="Gloridifice"
description='''
This is a mod added a Thirst and Drinking System to Minecraft.
'''
[[dependencies.watersource]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.watersource]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"

